version: '2'
services:
  service:
    build: .
    image: dslimexamples/node-compose-service
    ports:
      - "1300:1300"
    depends_on:
      - redis
  redis:
    image: redis:4.0-alpine
    ports:
      - "16379:6379"
