---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-redis
  labels:
    app: ${APP_NAME}-redis
spec:
  ports:
    - name: redis-16379
      port: 16379
      targetPort: 6379
  selector:
    app: ${APP_NAME}-redis
