---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}-redis
  labels:
    app: ${APP_NAME}-redis
spec:
  selector:
    matchLabels:
      app: ${APP_NAME}-redis
  template:
    metadata:
      labels:
        app: ${APP_NAME}-redis
    spec:
      containers:
        - name: redis
          image: redis:4.0-alpine
          ports:
            - containerPort: 6379
